Repository buzden/deptycheck, pull requests merged in 2025-05, with the labels that each got.

#268 [ cleanup ] Remove useless `Deriving.DepTyCheck` module
  deptycheck.ipkg
  src/Deriving/DepTyCheck.idr
  tests/derivation/core/defaulthint/DerivedGen.idr
Labels: code: cleanup, part: derivation

#269 [ ico ] Update the lib's icons
  icons/NOTICE
  icons/deptycheck-lib-alt.png
  icons/deptycheck-lib-html-logo.png
  icons/deptycheck-lib.ico
  icons/deptycheck-lib.png
Labels: code: enhancement, code: redesign, part: docs

#270 [ fix ] Treat implicit arguments when initing coverage info
  src/Test/DepTyCheck/Gen/Coverage.idr
  tests/lib/coverage/ty-and-con-withCov-014/PrintCoverage.idr
  tests/lib/coverage/ty-and-con-withCov-014/expected
  tests/lib/coverage/ty-and-con-withCov-014/run
  tests/lib/coverage/ty-and-con-withCov-014/test.ipkg
Labels: status: confirmed bug, issue: compilation error, code: fix, part: model coverage

#271 [ compat ] adjust to upstream changes
  src/Test/DepTyCheck/Gen.idr
Labels: part: generators, status: upstream, issue: compilation error, code: fix

#274 [ compat ] Be compatible with `contrib` library
  deptycheck.ipkg
  elab-util-extra/src/Language/Reflection/Expr.idr
  src/Deriving/DepTyCheck/Gen/ConsRecs.idr
  src/Deriving/DepTyCheck/Gen/Signature.idr
  src/Deriving/DepTyCheck/Util/ArgsPerm.idr
  src/Deriving/DepTyCheck/Util/DeepConsApp.idr
Labels: part: derivation, status: upstream, issue: compilation error, derive: entry, code: workaround, status: workarounded
